/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Model.Funcionario;
import DAO.FuncionarioDAO;

/**
 *
 * @author Usuário
 */

public class Funcionários extends javax.swing.JFrame {
    String idEdicao = "";

    /**
     * Creates new form Funcionários
     */
    public Funcionários() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtcargo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtlogin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        botaoCad = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablista = new javax.swing.JTable();
        botaoEx = new javax.swing.JButton();
        botaoAtt = new javax.swing.JButton();
        botaoBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoLimpaCampos = new javax.swing.JButton();
        txtsenha = new javax.swing.JTextField();
        txtbusca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuBarArquivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Fotos/persona-CB.png"))); // NOI18N

        jLabel8.setText("Nome:");

        jLabel10.setText("Cargo:");

        jLabel11.setText("Login:");

        jLabel12.setText("Senha:");

        botaoCad.setBackground(new java.awt.Color(0, 79, 158));
        botaoCad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoCad.setForeground(new java.awt.Color(255, 255, 255));
        botaoCad.setText("Cadastrar / Salvar");
        botaoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadActionPerformed(evt);
            }
        });

        tablista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablista);

        botaoEx.setBackground(new java.awt.Color(0, 79, 158));
        botaoEx.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoEx.setForeground(new java.awt.Color(255, 255, 255));
        botaoEx.setText("Excluir");
        botaoEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExActionPerformed(evt);
            }
        });

        botaoAtt.setBackground(new java.awt.Color(0, 79, 158));
        botaoAtt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoAtt.setForeground(new java.awt.Color(255, 255, 255));
        botaoAtt.setText("Editar");
        botaoAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAttActionPerformed(evt);
            }
        });

        botaoBuscar.setBackground(new java.awt.Color(0, 79, 158));
        botaoBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Funcionarios");

        botaoLimpaCampos.setBackground(new java.awt.Color(0, 79, 158));
        botaoLimpaCampos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoLimpaCampos.setForeground(new java.awt.Color(255, 255, 255));
        botaoLimpaCampos.setText("Limpar Campos");
        botaoLimpaCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimpaCamposActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 79, 158));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tela Inicial");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(botaoLimpaCampos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoCad)
                                        .addGap(6, 6, 6))
                                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(botaoAtt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoEx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoLimpaCampos)
                            .addComponent(botaoCad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoEx)
                            .addComponent(botaoAtt))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                .addGap(17, 17, 17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoBuscar)
                            .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        MenuBarArquivo.setText("Arquivo");

        jMenuItem1.setText("Tela Inicial");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuBarArquivo.add(jMenuItem1);

        jMenuBar1.add(MenuBarArquivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencherTabela() {
        try {
            this.idEdicao = "";

            FuncionarioDAO dao = new FuncionarioDAO();
            List<Model.Funcionario> lista = dao.listarFuncionarios();
            
            // Pega o modelo da tabela
            DefaultTableModel modelo = (DefaultTableModel) tablista.getModel();

            // Limpa antes de inserir novamente
            modelo.setRowCount(0);

            // Insere os dados
            for (Model.Funcionario f : lista) {
                Object[] linha = {
                    f.getId(),
                    f.getNome(),
                    f.getCargo(),
                };
                modelo.addRow(linha);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher tabela: " + e);
        }
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaInicial telai = new TelaInicial();
        telai.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void botaoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadActionPerformed
        try {
            String nome  = txtnome.getText();
            String cargo = txtcargo.getText();
            String login = txtlogin.getText();
            String senha = txtsenha.getText();

            Model.Funcionario funcionario = new Model.Funcionario();
            funcionario.setNome (nome );
            funcionario.setCargo(cargo);
            funcionario.setLogin(login);
            funcionario.setSenha(senha);

            FuncionarioDAO dao = new FuncionarioDAO();

            if (this.idEdicao != null && !this.idEdicao.trim().isEmpty()) {
                dao.salvarEdicaoFuncionarios(Integer.parseInt(this.idEdicao), funcionario);
                JOptionPane.showMessageDialog(null, "Funcionário atualizado com sucesso!");
                this.idEdicao = "";
            } else {
                dao.cadastrarFuncionario(funcionario);
                JOptionPane.showMessageDialog(null, "Funcionário cadastrado com sucesso!");
            }

            preencherTabela();
            limpacampos();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar funcionario" + erro);
        }
    }//GEN-LAST:event_botaoCadActionPerformed

    private void botaoLimpaCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimpaCamposActionPerformed
        try {
            limpacampos();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar produto" + erro);
        }
    }//GEN-LAST:event_botaoLimpaCamposActionPerformed

    private void limpacampos() {
        try {
            this.idEdicao = "";
            txtnome.setText("");
            txtcargo.setText("");
            txtlogin.setText("");
            txtsenha.setText("");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar produto" + erro);
        } 
    }

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        try {
            String pesquisa = txtbusca.getText();

            if (pesquisa.isEmpty()){
                this.preencherTabela();
            } else {
                FuncionarioDAO dao = new FuncionarioDAO();
                List<Model.Funcionario> lista = dao.pesquisarFuncionarios((String) pesquisa);

                DefaultTableModel modelo = (DefaultTableModel) tablista.getModel();
                
                modelo.setRowCount(0);

                for (Model.Funcionario f : lista) {
                    Object[] linha = {
                        f.getId(),
                        f.getNome(),
                        f.getCargo(),
                    };
                    modelo.addRow(linha);
                }
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar Funcionario" + erro);
        }
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExActionPerformed
        try {
            String id = (String) tablista.getValueAt(tablista.getSelectedRow(), 0);

            FuncionarioDAO dao = new FuncionarioDAO();
            dao.excluirProduto(Integer.parseInt(id));
            preencherTabela();

            JOptionPane.showMessageDialog(null, "Funcionario excluido com sucesso!");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir" + erro);
        }
    }//GEN-LAST:event_botaoExActionPerformed

    private void botaoAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAttActionPerformed
        try {
            String id    = (String) tablista.getValueAt(tablista.getSelectedRow(), 0);
            String nome  = (String) tablista.getValueAt(tablista.getSelectedRow(), 1);
            String cargo = (String) tablista.getValueAt(tablista.getSelectedRow(), 2);

            FuncionarioDAO dao = new FuncionarioDAO();
            List<Model.Funcionario> lista = dao.pesquisarAtualizar(id);

            if (!lista.isEmpty()) {
                Model.Funcionario funcionario = lista.get(0);
                this.idEdicao = funcionario.getId();
                txtnome.setText(funcionario.getNome());
                txtcargo.setText(funcionario.getCargo());
                txtlogin.setText(funcionario.getLogin());
                txtsenha.setText(funcionario.getSenha());
            }


        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir" + erro);
        }
    }//GEN-LAST:event_botaoAttActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          TelaInicial inicio = new TelaInicial();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Funcionários().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuBarArquivo;
    private javax.swing.JButton botaoAtt;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoCad;
    private javax.swing.JButton botaoEx;
    private javax.swing.JButton botaoLimpaCampos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablista;
    private javax.swing.JTextField txtbusca;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtsenha;
    // End of variables declaration//GEN-END:variables
}
